"""
tools/retrieval_tools.py — Retrieval tool functions for LangGraph agents.

All functions are plain Python with type annotations and docstrings.
The docstring is what the LLM reads to decide when to call the tool.
Every function is independently testable without a running LLM.

Functions:
  index_paper           — chunk, embed, add to ChromaDB + BM25
  search_vector_db      — pure semantic search
  hybrid_search         — BM25 + semantic (preferred)
  rerank_chunks         — cross-encoder rerank
  delete_paper_from_index — remove a paper's chunks
"""

from __future__ import annotations

import logging

from config import Config

logger = logging.getLogger(__name__)


def index_paper(parsed_paper: dict) -> int:
    """
    Chunk a ParsedPaper, embed the chunks, and add them to both ChromaDB
    and the BM25 index.  Returns the number of chunks indexed.

    Call this after every successful parse.  Idempotent — re-indexing the
    same paper_id overwrites existing chunks.
    """
    from retrieval.chunker import chunk_parsed_paper
    from retrieval.embeddings import get_embedding_model
    from retrieval.vector_store import get_vector_store
    from retrieval.bm25_index import get_bm25_index

    chunks = chunk_parsed_paper(parsed_paper)
    if not chunks:
        logger.info("No chunks produced for %s", parsed_paper.get("paper_id", "?"))
        return 0

    texts = [c["text"] for c in chunks]
    embeddings = get_embedding_model().embed_texts(texts)

    get_vector_store().add_chunks(chunks, embeddings)
    get_bm25_index().add_chunks(chunks)
    get_bm25_index().save()

    logger.info(
        "Indexed %d chunks for %s",
        len(chunks), parsed_paper.get("paper_id", "?"),
    )
    return len(chunks)


def search_vector_db(
    query: str,
    top_k: int | None = None,
    year_filter: int | None = None,
    source_filter: str | None = None,
) -> list[dict]:
    """
    Semantic search over ChromaDB chunks.

    Use for exact quotes or when a specific claim is needed.
    Prefer hybrid_search for general research queries.

    source_filter: optionally restrict to 'arxiv' | 'pubmed' | 'biorxiv' etc.
    Returns list of {chunk_id, text, paper_id, title, authors, year, source,
    section_heading, score}.
    """
    from retrieval.embeddings import get_embedding_model
    from retrieval.vector_store import get_vector_store

    top_k = top_k or Config.RETRIEVAL_K
    query_embedding = get_embedding_model().embed_query(query)
    return get_vector_store().search(
        query_embedding,
        top_k=top_k,
        year_filter=year_filter,
        source_filter=source_filter,
    )


def hybrid_search(
    query: str,
    top_k: int | None = None,
    year_filter: int | None = None,
    source_filter: str | None = None,
    use_hyde: bool | None = None,
) -> list[dict]:
    """
    BM25 + semantic search fused with Reciprocal Rank Fusion.

    Preferred over pure semantic for technical terms, gene names, drug names,
    and abbreviations where exact keyword matching matters.

    If use_hyde is True (or Config.USE_HYDE is True), the query is first
    expanded using a hypothetical document generated by the LLM.

    Returns list of {chunk_id, text, paper_id, title, authors, year, source,
    section_heading, score}.
    """
    from retrieval.hybrid_search import hybrid_search as _hybrid
    from retrieval.hyde import generate_hyde_document

    top_k = top_k or Config.RETRIEVAL_K
    effective_query = query

    if use_hyde is None:
        use_hyde = Config.USE_HYDE

    if use_hyde:
        effective_query = generate_hyde_document(query)

    return _hybrid(
        effective_query,
        top_k=top_k,
        year_filter=year_filter,
        source_filter=source_filter,
    )


def rerank_chunks(
    query: str,
    chunks: list[dict],
    top_k: int | None = None,
) -> list[dict]:
    """
    Cross-encoder rerank retrieved chunks (ms-marco-MiniLM-L-6-v2).

    Always call after hybrid_search or search_vector_db, before passing
    chunks to the LLM.  Returns the top_k most relevant chunks with
    updated 'score' values (raw cross-encoder logit).
    """
    from retrieval.reranker import get_reranker

    top_k = top_k or Config.RERANK_TOP_K
    return get_reranker().rerank(query, chunks, top_k=top_k)


def delete_paper_from_index(paper_id: str) -> None:
    """
    Remove all chunks for a paper from ChromaDB and the BM25 index.
    Safe to call even if the paper was never indexed.
    """
    from retrieval.vector_store import get_vector_store
    from retrieval.bm25_index import get_bm25_index

    get_vector_store().delete_paper(paper_id)
    get_bm25_index().delete_paper(paper_id)
    get_bm25_index().save()
    logger.info("Removed %s from retrieval index", paper_id)
